### ISSUE TITLE
Bad link for start.jbm.org in readme

### ISSUE THREAD

**Issue by apupier** [BootstrapJBPM/jbavsc#2]
it is redirecting to https://github.com/BootstrapJBPM/jbavsc/blob/master/start.jbpm.org instead of https://start.jbpm.org/

**Comment by tsurdilo** [comment]
fixed via https://github.com/apupier/jbavsc/commit/77c9696bbd68acd49e6b6f9c5e729aa3ea597a29

thanks for pull request
