### ISSUE TITLE
can't unzip generate jbpm zip package

### ISSUE THREAD

**Issue by humgal** [BootstrapJBPM/jbavsc#4]
crossnebula:test dliang$ ls
business-application.zip
crossnebula:test dliang$ unzip business-application.zip 
Archive:  business-application.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of business-application.zip or
        business-application.zip.zip, and cannot find business-application.zip.ZIP, period.
crossnebula:test dliang$

**Comment by tsurdilo** [comment]
@humgal can you check the size of the generated zipfile and tell me if its 0 bytes (empty) please? If so, can tell me if you are trying to generate your app while you are online and what OS you are using? Thanks.

**Comment by tsurdilo** [comment]
@humgal just published extension version 0.9.0 - can you please try it? It adds a offline check in which case you will get a message like this when trying to generate your app:

<img width="480" alt="screen shot 2019-02-13 at 3 48 06 pm" src="https://user-images.githubusercontent.com/119422/52742989-01567d00-2fa7-11e9-9a40-0c3ee5f6dc97.png">

and an empty zip will no longer be generated.
Can you let me know if this helps you please? Thanks.

**Comment by tsurdilo** [comment]
@humgal any more info on this? are you still having the issue with 0.9.0 version ? please let me know. thanks.

**Comment by humgal** [comment]
thanks.
after update jbpm plugin,my problem already been solved.

**Comment by humgal** [comment]
@tsurdilo well done，thanks

**Comment by tsurdilo** [comment]
@humgal good to hear issue is fixed for you. thanks for using extension!
