### ISSUE TITLE
Business Central can't retrieve Process Definitions from KIE-server

### ISSUE THREAD

**Issue by w39hh** [BootstrapJBPM/jbavsc#5]
First, thanks for a great extension, really helpful.
I am deploying the KIE server to connect to a remote running Business Central instance, using the following config
```
#server configuration, VS Code extension host IP  
server.address=10.94.7.24  
server.port=8090  

#assign the default REST base URL for a kie-server
cxf.path=/kie-server/services/rest

#kie server config
kieserver.serverId=dawnapp-service
kieserver.serverName=dawnapp-service
kieserver.location=http://10.94.7.24:8090/kie-server/services/rest/server
kieserver.controllers=http://bc-host:8080/business-central/rest/controller
```
Business Central recognizes the KIE server, and I can deploy containers to it using the Business Central UI (including deploying the demo container created by the extension and  stored on the KIE server itself).

However, when Business Central tries to query the KIE server to get the deployed `Process Definitions` the response is 406 (or 405) Method not allowed. Business Central is using the following:
```
http://10.94.7.24:8090/kie-server/services/rest/server/queries/processes/definitions?sort=ProcessName&sortOrder=false&page=0&pageSize=10  
```
The actual Business Central error message is
```
Unable to complete your request. The following exception occurred: Unexpected HTTP response code when requesting URI 'http://10.94.7.24:8090/kie-server/services/rest/server/queries/processes/definitions?sort=ProcessName&sortOrder=false&page=0&pageSize=10'! Error code: 406, message: .
```
When I try the same call in Postman, it **succeeds!**

When Business Central tries to get the running `Process Instances`, it uses
```
http://10.94.7.24:8090/kie-server/services/rest/server/queries/definitions/jbpmProcessInstances/filtered-data?mapper=RawList&page=0&pageSize=10  
```
And Business Central shows this error
```
Unable to complete your request. The following exception occurred: Unexpected HTTP response code when requesting URI 'http://10.94.7.24:8090/kie-server/services/rest/server/queries/definitions/jbpmProcessInstances/filtered-data?mapper=RawList&page=0&pageSize=10'! Error code: 406, message: .
```
When I try that call in Postman, it fails with the same error as Business Central.

I have tried multiple REST endpoints on the running VS Code KIE server using Postman, and all except this one return the expected response.  For example I can get a full list of /queries/definitions, including for jbpmProcessInistances.   Business Central has no problem querying the sample-server that gets installed alongside Business Central.  Is there some additional dependency or configuration required to support jbpmProcessInstances/filtered-data? endpoints? Any idea why I can get Process Definitions using Postman and Business Central gets 405?  Thanks.

I should mention, Business Central is running on a Linux server, I am running the VS Code extension on Windows (believe me, not my idea).

**Comment by tsurdilo** [comment]
Hi @w39hh  I think you might be running into allow header issues which typically means some sort of CORS issue. There are two places where you might want to look at, one in your jBPM Business app --  https://gist.github.com/tsurdilo/5ea1c2066fd982d2b360872d977cf3a6

and also in BC, where you need to enable CORS. I'm not expert with workbench by any means but here is one article that might help you -- https://groups.google.com/forum/#!topic/drools-setup/8w7N07BUMz8

Hope this helps!

**Comment by w39hh** [comment]
Thanks for your fast response, I did follow your instructions and used your Gist to modify DefaultWebSecurityConfig for the KIE server.  I will dig into the configuration for Business-Central /Wildfly. Thanks again.

**Comment by tsurdilo** [comment]
@w39hh no problem, hope you have luck with setting that up, I remember doing that (look at the lower part of post http://mswiderski.blogspot.com/2018/07/easy-workitem-installation-jbpm.html). I'm not sure if you need that filter as your path would be /rest/server, but maybe it will help some. 

@mswiderski if you have anything to add here please help :)

**Comment by w39hh** [comment]
Thanks for all your help.  I think it may have been as stupid as an authorization issue, the user under which Business Central was running may not have had appropriate permissions on the KIE server. I modified the authorizations in DefaultWebSecurityConfig for the KIE server and can now get past those errors. Also, did not realize that in Business Central the first time a container is deployed one apparently has to start an instance from Manage Process Instances (and choose the process from the container) before the process definitions in the container are visible in Manage Process Definitions? (not sure of this).

However, 
http://10.94.7.24:8090/kie-server/services/rest/server/queries/definitions/jbpmProcessInstances/filtered-data?mapper=RawList&page=0&pageSize=10 
Still returns method not allowed (405) in Postman, using a user (kieserver) with, I think, all necessary permissions on the KIE server.  But this has nothing to do with your Extension, so closing this.

**Comment by tsurdilo** [comment]
@w39hh glad to hear you figured it out - great job! thanks for using the extension. if you have any ideas on how to improve it (or if you want to contribute ;)) please let me know.

**Comment by Cvenkey** [comment]
Hi tsurdilo,

   I am also facing same issue even i check with latest version of kie (7.39.0.Final)
   Spring : 2.2.2v
   Wildfy : 7.36
  Connected Mode : Dev.
and I downloaded business application from start.jbpm.org and made below change in both app.prop app-dev.prop files 
spring.datasource.url=jdbc:h2:./target/spring-boot-jbpm

Caused by: org.kie.server.api.exception.KieServicesHttpException: Unexpected HTTP response code when requesting URI 'http://localhost:8090/rest/server/queries/processes/definitions?filter=&sort=ProcessName&sortOrder=false&page=0&pageSize=10'! Error code: 406, message:
        at org.kie.server.client.impl.AbstractKieServicesClientImpl.createExceptionForUnexpectedResponseCode(AbstractKieServicesClientImpl.java:622)
        
Can you please suggest for next.
Thanks.
